variable "project_id" {
  type        = string
  description = "GCP project id"
}

variable "region" {
  type        = string
  description = "GCP region"
  default     = "asia-south1"
}

variable "domain" {
  type        = string
  description = "Public domain serving the application"
}

variable "image_tag" {
  type        = string
  description = "Immutable image tag to deploy — the git SHA built in CI, never 'latest'"

  validation {
    condition     = var.image_tag != "latest"
    error_message = "Deploy an immutable tag. You cannot roll back to a tag that moves."
  }
}

variable "db_tier" {
  type        = string
  description = "Cloud SQL machine tier"
  default     = "db-custom-1-3840"
}

# There is deliberately no `db_password` variable.
#
# A password with a default in version control is a leaked credential, and one
# without a default is a value someone types into a shell and leaves in their
# history. The database credential is generated by Terraform into Secret
# Manager and referenced by name; nothing here ever holds it.
